---
- import_playbook: gw.yml
- import_playbook: volume-groups.yml
- import_playbook: ntp-server.yml
- import_playbook: ntp-client.yml
- import_playbook: bind.yml
- import_playbook: generate-key.yml
- import_playbook: fetch-key.yml
- import_playbook: distribute-key.yml
- import_playbook: swift-disks.yml
- import_playbook: osa-prep.yml
- import_playbook: osa-git.yml
- import_playbook: osa-deploy.yml
# - import_playbook: console-vm.yml
