---

osa_repo: 'https://github.com/openstack/openstack-ansible.git'
# osa_version: stable/queens
# osa_version: stable/pike
osa_version: 17.1.0
osa_destination: /opt/openstack-ansible
git_force: no

service_net_address: 10.208.0.0

controller_lxc_vg: /dev/xvdo
storage_cinder_vg: /dev/xvdo
compute_cinder_vg: /dev/xvdo

# Console Settings
my_cloud_name: osa_test_env
console_user_name: console-user
console_user_comment: "Console User"

# Configure Openstack Settings
my_cloud_username: demo-user1 # Used to create a user account on the Cloud
my_cloud_password: '{{ vault_my_cloud_password }}' # Password for the above account, stored in the vault.yml file
project_1: UI_Demo
project_1_desc: UI Demo Project
project_2: Heat_Demo
project_2_desc: Heat Demo Project
project_3: Terraform_Demo
project_3_desc: Terraform Demo Project
project_4: Ansible_Demo
project_4_desc: Ansible Demo Project

# Bind Settings
# bind_encapsulation_cidr: 10.240.0.0/22
# bind_br_flat_cidr: 172.29.252.0/22
# bind_br_mgmt_cidr: 172.29.236.0/22
# bind_br_storage_cidr: 172.29.244.0/22
# bind_storage_rep_cidr: 172.29.248.0/22
# bind_br_vxlan_cidr: 172.29.240.0/22
# bind_forwarder1: 8.8.8.8
# bind_forwarder2: 8.8.4.4
# bind_forwarder3: 69.20.0.164
# bind_forwarder4: 69.20.0.196
dns_servers: 69.20.0.164 69.20.0.196 #Only requried when Bind is not deployed - comment out this line if Bind is being deployed, and comment out the Bind lines above etc


# VPN Settings
vpn_network: 172.27.224.0 
vpn_netmask: 255.255.240.0
vpn_interface: br-flat

# Status Mail Settings - values are stored in encrypted vault file
send_mail: false
subject_prefix: 'openstack-multa:'
host: '{{ vault_host }}'
port: '{{ vault_port }}'
secure: '{{ vault_secure }}'
username: '{{ vault_username }}'
password: '{{ vault_password }}'
from: '{{ vault_from }}'
to: '{{ vault_to }}'
